# This workflow will build and test a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout badges branch to a badges directory nested inside first checkout
      uses: actions/checkout@v3
      with:
        ref: badges
        path: badges
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run texts
      run: mvn -B test
    - name: Publish test coverage results
      if: ${{ github.event_name != 'pull_request' }}
      uses: PavanMudigonda/jacoco-reporter@v4.5
      with:
        coverage_results_path: 'target/site/jacoco/jacoco.xml'
        coverage_report_title: 'Test coverage results'
        coverage_report_name: 'Test coverage results'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        minimum_coverage: 80
        fail_below_threshold: false
        publish_only_summary: true
    - name: Add coverage to PR
      if: ${{ github.event_name == 'pull_request'}}
      uses: madrapps/jacoco-report@v1.3
      with:
        paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 40
        min-coverage-changed-files: 80
    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2.7.0
      with:
        jacoco-csv-file: target/site/jacoco/jacoco.csv
        badges-directory: badges
        generate-coverage-badge: true
        coverage-badge-filename: jacoco.svg
        generate-branches-badge: true
        branches-badge-filename: branches.svg
        generate-coverage-endpoint: true
        coverage-endpoint-filename: jacoco.json
        generate-branches-endpoint: true
        branches-endpoint-filename: branches.json
        generate-summary: true
        summary-filename: coverage-summary.json
        coverage-label: coverage
        branches-label: branches
        colors: '#4c1 #97ca00 #a4a61d #dfb317 #fe7d37 #e05d44'
        intervals: 100 90 80 70 60 0
        on-missing-report: fail
        fail-if-coverage-less-than: 0
        fail-if-branches-less-than: 0
        fail-on-coverage-decrease: false
        fail-on-branches-decrease: false
    - name: Commit and push the coverage badges and summary file
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        cd badges
        if [[ `git status --porcelain *.svg *.json` ]]; then
          git config --global user.name 'github-actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add *.svg *.json
          git commit -m "Autogenerated coverage badges" *.svg *.json
          git push
        fi
